config/routes.rb
MyHub::Application.routes.draw do
  devise_for :users

  resources :projects

  root 'home#index'

  

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks
  validates_presence_of :title, :pitch
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates_presence_of :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name
  has_many :projects
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	#before_filter :authenticate_user!
	respond_to :json, :html
	#------------------------------GET--------------------------------------
	def index
		@projects = Project.all
		respond_with @projects
	end

	def show
		@project = Project.find(params[:id])
		respond_with @project
	end

	def new
		@project = Project.new(params[:project])
		respond_with @project
	end

	#------------------------------POST--------------------------------------
	def create
		@project = Project.new(params[:project].permit(:title, :pitch))
		
		if @project.save
		    redirect_to @project
		else
		    render 'new'
		end
		
	end
	#------------------------------PATCH---------------------------------------
	def edit
		@project = Project.find(params[:id])

		if params.has_key?(:project)
			@project.update(params[:project].permit(:title, :pitch))
			redirect_to @project
		else
			render 'edit'
		end
	end
	def update
		@project = Project.find(params[:id])

		if @project.update(params[:project].permit(:title, :pitch))
			redirect_to @project
		else
			render 'edit'
		end
	end

	#------------------------------DESTROY--------------------------------------
	def destroy
		@project = Project.find(params[:id])
		@project.destroy

		redirect_to projects_path
	end

	#------------------------------PRIVATE--------------------------------------
	private
		def project_params
			params.require(:project).permit(:title, :pitch)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<div ng-view=""></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="MyHub">
	<head>
	  <title>MyHub</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<% if user_signed_in? %>
	    <nav class="navbar navbar-fixed-bottom " role="navigation">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <br>
	        </div>

	        <!-- Collect the nav links, forms, and other content for toggling -->
	        <div class="collapse navbar-collapse navbar-ex1-collapse">
	          <ul class="nav navbar-nav">
	            <li><a href="#projects">Projects</a></li>
	            <li><a href="#services">Services</a></li>
	            <li><a href="#contact">Contact</a></li>
	            <% if user_signed_in? %>
		          	<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
				<% else %>
					<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
					<li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
				<% end %>
	          </ul>
	        </div><!-- /.navbar-collapse -->
	      </div><!-- /.container -->
	    </nav>
	    <% end %>
	    <div class="container">
	    	<a href="/"><h1>My Hub</h1></a>
	    	<% if user_signed_in? %>
				<p>Logged in as <strong><%= current_user.name %></strong>.</p>
			<% else %>
				<p>
					<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> | 
					<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
				</p>
			<% end %>
	    	<% if @projects %>
	    		<h4 class="pull-right">You Have <%= @projects.length %> Project(s)</h4>
			<% end %>	    	
	    </div>
	    <div class="container">
		    <% if notice %>
		    	<p class="notice alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
				<p class="alert alert-danger"><%= alert %></p>
			<% end %>
	    	<div ><%= yield %></div>
	    </div>

	</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited
      this project from being saved:</h2>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p><%= f.hidden_field :user_id, :value => current_user.id %></p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :pitch %><br>
    <%= f.text_area :pitch , size: "50x3" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<div class="sign">
	<h1>Editing project</h1>
 
	<%= render 'form' %>
	
	<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<div class="row">
	<div class="col-xs-4 col-sm-3">
		<% @projects.each do |project| %>
			<p>
				<%= link_to project.title, project %>
				<%= link_to '', project_path(project), method: :delete, data: { confirm: 'Are you sure?' },  :class => "glyphicon glyphicon-trash pull-right", :id => "tools"  %>
				<%= link_to '', project,  :class => "glyphicon glyphicon-ok pull-right", :id => "tools"  %>
				<%= link_to '', edit_project_path(project), :class => "glyphicon glyphicon-pencil pull-right", :id => "tools" %>
				
			</p>
		<% end %>
	</div>
	<div class="col-xs-10 col-sm-4 col-md-6">
	
		
	</div>

</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<hr>
<div class="sign">
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class="row row-offcanvas row-offcanvas-right">
	<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
		<h2><%= @project.title %></h2>
		<p>
			<%= link_to '', edit_project_path(@project), :class => "glyphicon glyphicon-pencil pull-left", :id => "tools" %> | 
			<small><%= link_to 'Back', projects_path %></small>
			</p>	
	</div>
    <div class="col-xs-12 col-sm-9">
    	<p><%= @project.pitch %></p>
    </div>
</div>